apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: {{.cluster_name.value}}
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  kubeDNS:
    provider: CoreDNS
  cloudProvider: aws
  configBase: s3://{{.kops_s3_bucket.value}}/{{.cluster_name.value}}
  dnsZone: {{.hosted_zone_id.value}}    
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    {{range $i, $az := .availability_zone_names.value}}
    - instanceGroup: master-{{.}}
      name: {{. | replace $.region.value "" }} {{/* converts ap-southeast-2a to a */}}
    {{end}}
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    {{range $i, $az := .availability_zone_names.value}}
    - instanceGroup: master-{{.}}
      name: {{. | replace $.region.value "" }} {{/* converts ap-southeast-2a to a */}}
    {{end}}
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.15.9
  masterPublicName: api.{{.cluster_name.value}}
  networkCIDR: {{.vpc_cidr_block.value}}
  networkID: {{.vpc_id.value}}
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  {{range $i, $id := .kops_private_subnet_ids.value}}
  - id: {{$id}}
    name: private-kops.{{index $.availability_zone_names.value $i}}.{{ $.cluster_name.value }}
    type: Private
    egress: {{index $.nat_gateways.value $i}}
    zone: {{index $.availability_zone_names.value $i}}
  {{end}}
  {{range $i, $id := .bastion_public_subnet_ids.value}}
  - id: {{$id}}
    name: utility.{{index $.availability_zone_names.value $i}}.{{ $.cluster_name.value }}
    type: Utility
    zone: {{index $.availability_zone_names.value $i}}
  {{end}}
  topology:
    bastion:
      bastionPublicName: bastion.{{ .cluster_name.value }}
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: {{.cluster_name.value}}
  name: nodes
spec:
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t2.small
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  {{range $i, $id := .availability_zone_names.value}}
  - private-kops.{{index $.availability_zone_names.value $i}}.{{ $.cluster_name.value }}
  {{end}}

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: {{.cluster_name.value}}
  name: bastions
spec:
  associatePublicIp: true
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t2.small
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility.{{index $.availability_zone_names.value 0}}.{{ $.cluster_name.value }}  
